'use strict';

/**
 * PHP 7.4 number semantics, reproduced exactly (PROVIDED INFRASTRUCTURE, LOCKED).
 *
 * osCommerce's pricing math depends on how PHP converts between floats and
 * strings, not only on arithmetic. For example tep_round() rounds by cutting
 * the *string* form of a float, and order.php builds a tax divisor by string
 * concatenation. JavaScript's String(n) and Number(s) behave differently, so
 * the domain code must use these helpers wherever the legacy code relied on
 * PHP's implicit conversions.
 *
 * Each helper is checked against fixtures generated by real PHP 7.4
 * (fixtures/golden/functions/php_*.json).
 */

const PRECISION = 14; // php.ini `precision`, which (string)$float uses

/** Exact decimal expansion of a finite, positive double: value = digits × 10^exp10. */
function exactDecimal(x) {
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, x);
  const hi = view.getUint32(0);
  const lo = view.getUint32(4);
  const expBits = (hi >>> 20) & 0x7ff;
  let mantissa = (BigInt(hi & 0xfffff) << 32n) | BigInt(lo);
  let exp2;
  if (expBits === 0) {
    exp2 = -1074;
  } else {
    mantissa |= 1n << 52n;
    exp2 = expBits - 1075;
  }
  if (exp2 >= 0) return { digits: (mantissa << BigInt(exp2)).toString(), exp10: 0 };
  return { digits: (mantissa * 5n ** BigInt(-exp2)).toString(), exp10: exp2 };
}

/** Round a digit string at `keep` digits, half-to-even on exact ties (C library behaviour). */
function roundDigits(digits, keep) {
  if (keep < 0) return { digits: '', carried: false };
  if (digits.length <= keep) return { digits, carried: false };
  const head = digits.slice(0, keep);
  const next = digits[keep];
  const tailNonZero = /[1-9]/.test(digits.slice(keep + 1));
  const lastEven = keep === 0 ? true : Number(head[keep - 1]) % 2 === 0;
  const up = next > '5' || (next === '5' && (tailNonZero || !lastEven));
  if (!up) return { digits: head, carried: false };
  if (head === '') return { digits: '1', carried: true };
  const bumped = (BigInt(head) + 1n).toString();
  if (bumped.length > head.length) return { digits: bumped.slice(0, keep), carried: true };
  return { digits: bumped, carried: false };
}

/**
 * (string)$float in PHP 7.4 (precision = 14, "%.14G" style).
 *   0.1 + 0.2         -> "0.3"
 *   1e14              -> "1.0E+14"
 *   0.00001           -> "1.0E-5"
 *   12345678901234.5  -> "12345678901234"
 * @param {number} x
 * @returns {string}
 */
function phpFloatToString(x) {
  if (Number.isNaN(x)) return 'NAN';
  if (x === Infinity) return 'INF';
  if (x === -Infinity) return '-INF';
  if (x === 0) return Object.is(x, -0) ? '-0' : '0';

  const sign = x < 0 ? '-' : '';
  const { digits, exp10 } = exactDecimal(Math.abs(x));
  let decpt = digits.length + exp10; // position of the decimal point relative to the first digit
  const r = roundDigits(digits, PRECISION);
  let mant = r.digits;
  if (r.carried) decpt += 1;
  mant = mant.replace(/0+$/, '') || '0';

  if (decpt < -3 || decpt > PRECISION) {
    const e = decpt - 1;
    const rest = mant.slice(1) || '0';
    return `${sign}${mant[0]}.${rest}E${e < 0 ? '-' : '+'}${Math.abs(e)}`;
  }
  if (decpt <= 0) return `${sign}0.${'0'.repeat(-decpt)}${mant}`;
  if (mant.length <= decpt) return sign + mant + '0'.repeat(decpt - mant.length);
  return `${sign}${mant.slice(0, decpt)}.${mant.slice(decpt)}`;
}

/**
 * PHP's implicit string conversion: strings stay as they are, numbers go
 * through phpFloatToString. Use it wherever legacy code does `.` concatenation,
 * strpos()/substr()/str_replace() on a number, and so on.
 * @param {number|string} value
 * @returns {string}
 */
function phpToString(value) {
  if (typeof value === 'string') return value;
  if (typeof value === 'number') return phpFloatToString(value);
  if (value === null || value === undefined || value === false) return '';
  if (value === true) return '1';
  throw new TypeError(`phpToString: unsupported value ${value}`);
}

const NUMERIC_PREFIX = /^[ \t\n\r\v\f]*([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)/;

/**
 * PHP 7.4's numeric coercion, as used by arithmetic and by comparing a string
 * with a number: the leading numeric part counts and the rest is ignored.
 *   "299.9900" -> 299.99   "1.01.0E-5" -> 1.01   "abc" -> 0   "-" -> 0
 * @param {number|string|null|undefined|boolean} value
 * @returns {number}
 */
function phpToNumber(value) {
  if (typeof value === 'number') return value;
  if (value === null || value === undefined || value === false || value === '') return 0;
  if (value === true) return 1;
  const m = NUMERIC_PREFIX.exec(String(value));
  return m ? Number(m[1]) : 0;
}

// ---- round() / number_format() --------------------------------------------

function intPow10(power) {
  if (power < 0 || power > 22) return 10 ** power;
  return Number(`1e${power}`);
}

function roundHelper(value) {
  return value >= 0.0 ? Math.floor(value + 0.5) : Math.ceil(value - 0.5);
}

/**
 * PHP 7.4 round($value, $places) with PHP_ROUND_HALF_UP, including its
 * "pre-rounding" to 15 significant digits (so round(1.955, 2) is 1.96).
 * @param {number} value
 * @param {number} places
 * @returns {number}
 */
function phpRound(value, places) {
  if (!Number.isFinite(value) || value === 0) return value;
  const precisionPlaces = 14 - Math.floor(Math.log10(Math.abs(value)));
  const f1 = intPow10(Math.abs(places));
  let tmp;
  if (precisionPlaces > places && precisionPlaces - 15 < places) {
    let usePrecision = precisionPlaces < -(4 * 15) ? -(4 * 15) : precisionPlaces;
    const f2 = intPow10(Math.abs(usePrecision));
    tmp = roundHelper(usePrecision >= 0 ? value * f2 : value / f2);
    usePrecision = Math.max(-(4 * 15), places - usePrecision);
    tmp = tmp / intPow10(Math.abs(usePrecision));
  } else {
    tmp = places >= 0 ? value * f1 : value / f1;
    if (Math.abs(tmp) >= 1e15) return value;
  }
  tmp = roundHelper(tmp);
  return places > 0 ? tmp / f1 : tmp * f1;
}

/** printf("%.*F", decimals, x) for finite x >= 0. */
function toFixedExact(x, decimals) {
  if (x === 0) return decimals > 0 ? `0.${'0'.repeat(decimals)}` : '0';
  const { digits, exp10 } = exactDecimal(x);
  const intLen = digits.length + exp10; // digits before the decimal point
  const keep = intLen + decimals;
  let r = roundDigits(digits, keep);
  let all = r.digits;
  let len = intLen;
  if (r.carried) len += 1;
  if (keep <= 0 && !r.carried) all = '';
  // left-pad so that there are `len` integer digits (len may be <= 0)
  const needed = Math.max(len, 0) + decimals;
  if (len <= 0) all = '0'.repeat(-len) + all;
  all = all.padEnd(needed, '0');
  const intPart = (len > 0 ? all.slice(0, len) : '') || '0';
  const fracPart = all.slice(Math.max(len, 0), Math.max(len, 0) + decimals);
  return decimals > 0 ? `${intPart}.${fracPart}` : intPart;
}

/**
 * PHP 7.4 number_format($number, $decimals, $decPoint, $thousandsSep).
 * @param {number|string} number
 * @param {number} decimals
 * @param {string} decPoint
 * @param {string} thousandsSep
 * @returns {string}
 */
function phpNumberFormat(number, decimals, decPoint = '.', thousandsSep = ',') {
  let d = phpToNumber(number);
  const dec = Math.max(0, decimals);
  d = phpRound(d, dec);
  let negative = false;
  if (d < 0) {
    negative = true;
    d = -d;
  }
  if (!Number.isFinite(d)) return (negative ? '-' : '') + (Number.isNaN(d) ? 'nan' : 'inf');
  const fixed = toFixedExact(d, dec);
  if (negative && d === 0) negative = false;
  const [intPart, frac] = fixed.split('.');
  let grouped = '';
  for (let i = 0; i < intPart.length; i++) {
    if (i > 0 && (intPart.length - i) % 3 === 0) grouped += thousandsSep;
    grouped += intPart[i];
  }
  return (negative ? '-' : '') + grouped + (dec > 0 ? decPoint + frac : '');
}

module.exports = {
  phpFloatToString,
  phpToString,
  phpToNumber,
  phpRound,
  phpNumberFormat,
};
